### ISSUE TITLE
When shuffling songs, the UI shows the shuffled order correctly. However, when calling skipToNext() and skipToPrevious(), _player will play the song in the original order, not the shuffled order

### ISSUE THREAD

**Issue by duypham312** [suragch/flutter_audio_service_demo#1]
As the title mentioned, `skipToNext()` and `skipToPrevious()` functions do not work properly when `shuffleModeEnabled` is true. For example, if the initial order is `[song 1, song 2, song 3]` and the shuffled order is `[song 1, song 3, song 2]`, when skipping to the second song in the shuffled order (`song 3` with the `index` is `1` in that array), calling `skipToNext()` will play `song 2` even though the UI will show `song 3` as the current song being played. I think this problem comes from the implementation of `skipToNext()` and `skipToPrevious()` that calling `seek(Duration.zero, index: index)` because `seek(Duration.zero, index: index)` operates on the initial order, not the shuffled order.

**Comment by suragch** [comment]
I'm not observing that behavior:

![order](https://user-images.githubusercontent.com/10300220/126956650-8d10514c-e74b-48b9-935d-98744ef4ed74.gif)

**Comment by suragch** [comment]
Oh, I understand now. You're talking about the audio. The title is changing but for some reason the audio is not matching the title. Let me look more into it.

**Comment by duypham312** [comment]
> Oh, I understand now. You're talking about the audio. The title is changing but for some reason the audio is not matching the title. Let me look more into it.

Yeah, that's what I meant

**Comment by suragch** [comment]
I'm a little stuck. I'm not sure how to solve this. If you find the solution can you let me know?

**Comment by duypham312** [comment]
Actually, I had to use a temporary solution. First of all, I calling `seekToNext()` and `seekToPrevious()` instead of `_skip()`. Then, I got the index of the song being played by the `_player` in the shuffled list by the following way:
```
_audioPlayer.durationStream.listen((duration) {
  var index = _audioPlayer.currentIndex;
  final newQueue = queue.value;

  if (index == null || newQueue.isEmpty) return;

  if (_audioPlayer.shuffleModeEnabled) {
    index = _audioPlayer.shuffleIndices!.indexOf(index);
  }

  final oldMediaItem = newQueue[index];
  final newMediaItem = oldMediaItem.copyWith(duration: duration);
  newQueue[index] = newMediaItem;

  queue.add(newQueue);
  mediaItem.add(newMediaItem);
});

_audioPlayer.currentIndexStream.listen((index) {
  final playlist = queue.value;
  if (index == null || playlist.isEmpty) return;

  if (_audioPlayer.shuffleModeEnabled) {
    index = _audioPlayer.shuffleIndices!.indexOf(index);
  }

  mediaItem.add(playlist[index]);
});
```
This solution can temporarily make the song's title sync with the song played by the `_player`. However, in my case, the `player` plays the next song without following the shuffled order. I hope this temporary solution can help you find a more effective solution to this problem

**Comment by duypham312** [comment]
In addition, this is how I implement `skipToQueueItem(int index)`
```
@override
Future<void> skipToQueueItem(int index) async {
  if (index < 0 || index >= queue.value.length) return;

  if (_audioPlayer.shuffleModeEnabled) {
    index = _audioPlayer.shuffleIndices![index];
  }

  _audioPlayer.seek(Duration.zero, index: index);
}
```
Besides, if you have a more efficient solution, you can share it in the issue that I have opened [here](https://github.com/ryanheise/just_audio/issues/457#issuecomment-886077905)

**Comment by suragch** [comment]
@duypham312 Thank you for posting the solution you have so far. I reproduced your results. Seeking to next and previous works but when one song finishes it automatically loads the incorrect song even though shuffling mode is enabled. 

Steps to reproduce (for others interested in this problem):

1. Replace the respective methods in audio_handler.dart with the following:

```dart
void _listenForDurationChanges() {
  _player.durationStream.listen((duration) {
    var index = _player.currentIndex;
    final newQueue = queue.value;
    if (index == null || newQueue.isEmpty) return;
    if (_player.shuffleModeEnabled) {
      index = _player.shuffleIndices!.indexOf(index);
    }
    final oldMediaItem = newQueue[index];
    final newMediaItem = oldMediaItem.copyWith(duration: duration);
    newQueue[index] = newMediaItem;
    queue.add(newQueue);
    mediaItem.add(newMediaItem);
  });
}

void _listenForCurrentSongIndexChanges() {
  _player.currentIndexStream.listen((index) {
    final playlist = queue.value;
    if (index == null || playlist.isEmpty) return;
    if (_player.shuffleModeEnabled) {
      index = _player.shuffleIndices!.indexOf(index);
    }
    mediaItem.add(playlist[index]);
  });
}

  @override
  Future<void> skipToQueueItem(int index) async {
    if (index < 0 || index >= queue.value.length) return;
    if (_player.shuffleModeEnabled) {
      index = _player.shuffleIndices![index];
    }
    _player.seek(Duration.zero, index: index);
  }

  @override
  Future<void> skipToNext() async {
    _player.seekToNext();
  }

  @override
  Future<void> skipToPrevious() async {
    _player.seekToPrevious();
  }
```

2. Run the demo app
3. Press the shuffle button until the playlist order says Song 1, Song 3, Song 2.
4. Play the first song and move the thumb on the seek bar so that it is almost finished. Then let it finish and automatically progress to the next song.

The next played song is Song 2 even though it should be Song 3.

**Comment by suragch** [comment]
I added a note to the shuffle section of the tutorial alerting readers to the bug and directing them here.

**Comment by suragch** [comment]
The source code for [just_audio_background](https://pub.dev/packages/just_audio_background) might provide some clues, but this is pretty different than my tutorial setup.

https://github.com/ryanheise/just_audio/blob/master/just_audio_background/lib/just_audio_background.dart

**Comment by duypham312** [comment]
@suragch Hey, have you tried to reproduce this error on Android? This bug has gone when I test on my android phone.

**Comment by duypham312** [comment]
I think I found the cause of the bug related to auto-next. The `_player.setShuffleModeEnabled(true)` is called before the `_player.shuffle()` is called and that resulted in the problem as I mentioned. When I call `await _player.shuffle()` before `_player.setShuffleModeEnabled(true)`, it works properly.

**Comment by duypham312** [comment]
@suragch hey, I found another bug related to the shuffle mode. If I play Song 3 while the shuffle mode is on and let it end, the app will crash without printing any error message.

**Comment by suragch** [comment]
@duypham312 Nice job on finding a workaround for the auto-next issue! 

The play-song-3-on-shuffle-mode bug seems to only cause a crash on iOS and macOS. Android and web work for me.

**Comment by suragch** [comment]
I've updated the tutorial and the project code up to this point. Even though there is still a bug with shuffling, it's better than it was before.

**Comment by duypham312** [comment]
@suragch hey, Ryanheise just informed me about the new `fix/queue` branch, I tested with this branch and the app doesn't crash anymore.

**Comment by suragch** [comment]
@duypham312 That's great! Could you ping me again when that branch gets merged?

**Comment by duypham312** [comment]
That branch has been merged, you can update the tutorial now

**Comment by suragch** [comment]
I've updated the tutorial. Thank you for your help in resolving this problem! I'll close the issue now.
