### ISSUE TITLE
How to setup `PRODUCT_BUNDLE_IDENTIFIER` in `ios/Runner.xcodeproj/project.pbxproj`?

### ISSUE THREAD

**Issue by tomasbaran** [suragch/flutter_audio_service_demo#18]
It works with your bundle ID but not with mine. How shall I set my bundle ID to work with the audio in the background, please?

Here are more details of the issue: https://stackoverflow.com/questions/71356022/changing-product-bundle-identifier-in-project-pbxproj-breaks-audio-in-the-ba

**Comment by suragch** [comment]
I'm not sure but I added a bounty on your question.

**Comment by tomasbaran** [comment]
Thanks a lot @suragch
