### ISSUE TITLE
MediaItem and IndexedAudioSource aren't in sync in shuffleMode

### ISSUE THREAD

**Issue by AssassinAguilar** [suragch/flutter_audio_service_demo#19]
Hello Sir, I have completely followed your tutorial and I am still having problem in syncing MediaItem and IndexedAudioSource like some song is playing and my app shows details of some other song in shuffle mode.

**Comment by erayhaydar** [comment]
Hi @AssassinAguilar, I have the same problem. How did you fix it ?

**Comment by erayhaydar** [comment]
I found the problem, change this functions like that.

`  void _listenForDurationChanges() {
    _player.durationStream.listen((duration) {
      var index = _player.currentIndex;
      final newQueue = queue.value;

      if (index == null || newQueue.isEmpty) return;

      if (_player.shuffleModeEnabled) {
        index = _player.shuffleIndices!.indexOf(index);
      }

      final oldMediaItem = newQueue[index];
      final newMediaItem = oldMediaItem.copyWith(duration: duration);
      newQueue[index] = newMediaItem;

      queue.add(newQueue);
      mediaItem.add(newMediaItem);
    });
  }

  void _listenForCurrentSongIndexChanges() {
    _player.currentIndexStream.listen((index) {
      final playlist = queue.value;
      if (index == null || playlist.isEmpty) return;
      if (_player.shuffleModeEnabled) {
        index = _player.shuffleIndices!.indexOf(index);
      }
      mediaItem.add(playlist[index]);
    });
  }`

**Comment by AssassinAguilar** [comment]
Hi @erayhaydar, I have switched to the official tutorial of audio_service in https://github.com/ryanheise/audio_service/blob/minor/audio_service/example/lib/example_playlist.dart and if you want to add duration later rather than in mediaItem change the current song function with
```
Rx.combineLatest5<int?, List<MediaItem>, bool, List<int>?, Duration?,
                MediaItem?>(
            _player.currentIndexStream,
            queue,
            _player.shuffleModeEnabledStream,
            _player.shuffleIndicesStream,
            _player.durationStream,
            (index, queue, shuffleModeEnabled, shuffleIndices, duration) {
      final queueIndex =
          getQueueIndex(index, shuffleModeEnabled, shuffleIndices);
      return (queueIndex != null && queueIndex < queue.length)
          ? queue[queueIndex].copyWith(duration: duration)
          : null;
    })
        .debounceTime(const Duration(milliseconds: 750))
        .whereType<MediaItem>()
        .distinct()
        .listen(mediaItem.add);
```

**Comment by erayhaydar** [comment]
@AssassinAguilar Thank you!
