### ISSUE TITLE
Killing the audio player app should also kill the audio and notification

### ISSUE THREAD

**Issue by NaagAlgates** [suragch/flutter_audio_service_demo#2]
Hello @ryanheise, Thank you for your amazing work. 

Possible Bug / A question:

**To Reproduce**

* Play an audio
* I can see the notification filled with current media item details and system controls such as play, stop, and other buttons.
* While playing the audio, I killed the app
* The app is killed
* But the notification is not removed.

**Expected behavior**
Ideally, the notification should be removed and the audio should stop playing on killing the main app.

**Minimal reproduction project**
Code to reproduce: https://github.com/suragch/flutter_audio_service_demo

audio_service version: `0.18`

**Flutter SDK version**

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.4 20F71 darwin-x64, locale en-IN)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.58.2)
[✓] Connected device (3 available)
```
Device: Moto G, Pixel 3XL
Android version: 7, 11

Screenshot:
![image](https://user-images.githubusercontent.com/14884575/127582952-7656354b-19b0-4900-957a-bb7464e0301b.png)
![image](https://user-images.githubusercontent.com/14884575/127582993-cd23f854-a812-47f9-a09b-110f6f0a56de.png)
![image](https://user-images.githubusercontent.com/14884575/127583023-889697c7-5644-41d1-84da-9a48afa68f34.png)

If there is a solution already, please excuse and request you to share the link or minimal code.

**Comment by suragch** [comment]
Did you mean to open this issue on the [audio_service](https://github.com/ryanheise/audio_service) repo?

**Comment by NaagAlgates** [comment]
Yes, I did.

**Comment by NaagAlgates** [comment]
Yes. :)

**Comment by gOzaru** [comment]
Add this code below inside `main.dart`

```dart
  @override
  void dispose() {
    _audioHandler.customAction("dispose");
    super.dispose();
  }
```
