### ISSUE TITLE
Bad notification(tag=null, id=1124) posted from package com.naamdham, crashing app

### ISSUE THREAD

**Issue by afjal1** [suragch/flutter_audio_service_demo#23]
D/AndroidRuntime( 9881): Shutting down VM
E/AndroidRuntime( 9881): FATAL EXCEPTION: main
E/AndroidRuntime( 9881): Process: com.myapp.package, PID: 9881
E/AndroidRuntime( 9881): android.app.RemoteServiceException: Bad notification(tag=null, id=1124) posted from package com.naamdham, crashing app(uid=10284, pid=9881): Couldn't inflate contentViewsjava.lang.IndexOutOfBoundsException: Index: 3, Size: 3
E/AndroidRuntime( 9881): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2093)
E/AndroidRuntime( 9881): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 9881): 	at android.os.Looper.loop(Looper.java:236)
E/AndroidRuntime( 9881): 	at android.app.ActivityThread.main(ActivityThread.java:8107)
E/AndroidRuntime( 9881): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 9881): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
E/AndroidRuntime( 9881): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
I/Process ( 9881): Sending signal. PID: 9881 SIG: 9
Lost connection to device.
Exited

**Comment by afjal1** [comment]
My App is Crashing on some devices with this exception .
Can You help me to solve the issue?

**Comment by suragch** [comment]
I've updated the example app that was also crashing. I'm not sure if it was the same issue or not but it isn't crashing anymore for me.

**Comment by afjal1** [comment]
I already solved it Thanks
