### ISSUE TITLE
Lock Screen shows Audio even after remove()

### ISSUE THREAD

**Issue by elvisgn** [suragch/flutter_audio_service_demo#25]
Hi,
First of all, thank you for the great article and demo.

I have a simple podcasting usecase where I just play one audio file and remove it on page `dispose()`. No playlists etc.

I have managed to add and remove the audio file, but I noticed that even after removing the audio file from the queue using `audioHandler.remove()`, it still shows up on the Lock Screen (screenshot attached)

![Simulator Screenshot - iPhone 13 Pro - 2023-11-29 at 12 31 37](https://github.com/suragch/flutter_audio_service_demo/assets/8165850/b96712a9-facd-4d2e-9751-cc1497c7becd)

The buttons and progressBar work on the screen with no sound (that's obvious).

How do I completely remove the MediaItem from Lock Screen?

Thanks.

**Comment by elvisgn** [comment]
Hi,
Looks like this is not a problem on an actual device, only on iOS simulator. Guess we can close the ticket.

Thanks.

**Comment by suragch** [comment]
Sorry, I was busy last week so I didn't get around to responding then. That's good to hear that it at least works on a real device. I'm not sure why there is that strange behavior on the simulator. Thank you for the follow-up comment.
